### ISSUE TITLE
Please update your example, this is simple things but very annoying when take simple example which does not work

### ISSUE THREAD

**Issue by alexanderm2018** [hashicorp/nomad-java-sdk#12]
here is the working version against your latest version from maven repo.

        NomadApiConfiguration config =
                new NomadApiConfiguration.Builder()
                        .setAddress("http://192.168.100.100:4646")
                        .build();

        NomadApiClient apiClient = new NomadApiClient(config);

**Comment by dadgar** [comment]
@alexanderm2018 Sorry about that! We would gladly take PRs for small issues like this!
