### ISSUE TITLE
Unable to list allocations for deployment

### ISSUE THREAD

**Issue by c2nes** [hashicorp/nomad-java-sdk#13]
`DeploymentsApi.allocations` uses the path `"/v1/deployment/" + deploymentId + "/allocations"`, but this should be `"/v1/deployment/allocations/" + deploymentId` per https://www.nomadproject.io/api/deployments.html#list-allocations-for-deployment

**Comment by cgbaker** [comment]
thanks, @c2nes , sorry for the delay on addressing this. will be available in the upcoming 0.8.x release of the SDK.
