### ISSUE TITLE
API config builder not working with PKCS#8 TLS key file

### ISSUE THREAD

**Issue by hpuac** [hashicorp/nomad-java-sdk#15]
## Issue
When generating a key with `openssl genpkey -algorithm RSA`, the default output format is a PKCS#8 TLS key file.
Unfortunately the config builder is not working with this file and only works with a PKCS#1 TLS key file.

## Technical analysis
A PKCS#1 TLS key file starts with `-----BEGIN RSA PRIVATE KEY-----`.
A PKCS#8 TLS key file starts with `-----BEGIN PRIVATE KEY-----`.
In the [TlsUtils](https://github.com/hashicorp/nomad-java-sdk/blob/master/sdk/src/main/java/com/hashicorp/nomad/javasdk/TlsUtils.java) class, the [loadPemKey function](https://github.com/hashicorp/nomad-java-sdk/blob/master/sdk/src/main/java/com/hashicorp/nomad/javasdk/TlsUtils.java#L47) is calling `readObject` of the [bouncycastle openssl PEMParser](https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/openssl/PEMParser.java#L58). 
This function is returning a `PEMKeyPair` if it's a PKCS#1 TLS key, or a `PrivateKeyInfo` if it's a PKCS#8 TLS key file.
The [loadPemKey function](https://github.com/hashicorp/nomad-java-sdk/blob/master/sdk/src/main/java/com/hashicorp/nomad/javasdk/TlsUtils.java#L51) is then doing a cast to a `PEMKeyPair` that is failing in case that we passed in a PKCS#8 TLS key file.

## Request
Please make the config builder able of using a PKCS#8 TLS key file.
Also the nomad cli tools are capable of handling both types of key files.

## Resources
https://stackoverflow.com/questions/20065304/differences-between-begin-rsa-private-key-and-begin-private-key#20065522

**Comment by cgbaker** [comment]
support added in #21 , will be part of upcoming v0.8.6 release
