### ISSUE TITLE
Can not set reschedule stanza

### ISSUE THREAD

**Issue by Nagist91** [hashicorp/nomad-java-sdk#16]
Nomad has already provided a way to set reschedule info for a job or group through its api, 
but nomad-java-sdk cannot do that.
Here's the HTTP API page:
https://www.nomadproject.io/docs/job-specification/reschedule.html

**Comment by cgbaker** [comment]
API support as of 0.8.6 has been merged into master and should be part of the imminent 0.8.6 release of the SDK
