### ISSUE TITLE
Jobs api's bug

### ISSUE THREAD

**Issue by Nagist91** [hashicorp/nomad-java-sdk#22]
when use the apiClient.getJobsApi().allocations(jobId) function, if the allocation restart, get the error message below:
Failed to parse Date value '2018-11-12T10:22:51.321156944+08:00': Can not parse date "2018-11-12T10:22:51.321156944+0800": while it seems to fit format 'yyyy-MM-dd'T'HH:mm:ss.SSSZ', parsing fails (leniency? null))
through reference chain: java.util.ArrayList[0]->com.hashicorp.nomad.apimodel.AllocationListStub["TaskStates"]->java.util.LinkedHashMap["task"]->com.hashicorp.nomad.apimodel.TaskState["LastRestart"]

**Comment by cgbaker** [comment]
the Nomad agent should be running on a machine with timezone UTC; see https://github.com/hashicorp/nomad-java-sdk/issues/6#issuecomment-432413422
