### ISSUE TITLE
API needs to be re-generated to support Nomad v0.10.2

### ISSUE THREAD

**Issue by chrismikehogan** [hashicorp/nomad-java-sdk#37]
We leverage the Java API to interact with Nomad, and want to use Device stanza for GPU workloads, but the current latest version of the SDK does not include Device in its models.

**Comment by chrismikehogan** [comment]
@cgbaker Is this something that Hashi would like community help for, or can we request that the SDK be updated to reflect models and features of latest Nomad?

**Comment by cgbaker** [comment]
@chrismikehogan , thanks for the report. our new Nomad Ecosystem team at HashiCorp is still in the process of getting stuff like this automated, but we're working on making these releases more timely. in the meantime, reminders like this are always welcome. i'll work on getting an updated Java SDK out this week. thanks for the report!

**Comment by chrismikehogan** [comment]
Thanks for the assist!

**Comment by cgbaker** [comment]
hey @chrismikehogan , i'm working on this now and while on travel next week, will get this out ASAP.

**Comment by chrismikehogan** [comment]
Thanks for the update!

**Comment by cricket007** [comment]
Placing this back here for reference. 

https://github.com/hashicorp/nomad-scala-sdk/issues/3#issuecomment-588326497

**Comment by cricket007** [comment]
Along with Device, Spread would be nice to have

https://nomadproject.io/docs/job-specification/spread/

**Comment by cgbaker** [comment]
v0.9.7.0 released on friday, with support for `device`, `spread`, and other features from `0.9.x`. Please let me know if there are any issues. I will leave this issue open as I update towards v0.10.4.

**Comment by chrismikehogan** [comment]
Thanks for the help @cgbaker ~

**Comment by chrismikehogan** [comment]
Wanted to note that the `unmappedProperties` getter/setter was a huge help in this case. Gave us a stop-gap solution pending this SDK upgrade. 

Thanks again!

**Comment by cgbaker** [comment]
update: releases supporting `0.10.0`, `0.10.2`, and `0.10.5` have been published and are available on maven central. 

closing this.
