### ISSUE TITLE
Unit/Integration Testing

### ISSUE THREAD

**Issue by cricket007** [hashicorp/nomad-java-sdk#39]
I see there is a community offered [Embedded Consul](https://github.com/pszymczyk/embedded-consul)

Could we get an _Embedded Nomad_ that runs `nomad agent -dev` and can be addressed as a JUnit Rule on `localhost:4646` ?

cc @chrismikehogan

**Comment by cgbaker** [comment]
That's neat, but I don't see us having the bandwidth to do that any time soon.

**Comment by cricket007** [comment]
That's fine, so what is the supported way to run proper integration testing with this repo rather than mocking all the classes?

**Comment by cgbaker** [comment]
The test suite currently runs a Nomad binary, no mocking.

**Comment by cricket007** [comment]
I mean for those of us actually using the Java SDK for other work. How do you suggest running Unit or Integration Tests? Also run the binary? That is effectively what the Embedded Consul project I linked to does, just within the JVM rather than manually spun up from the CLI ahead of time.

**Comment by cgbaker** [comment]
I don't manually spin up the nomad agent using the CLI. The test utils
package in the SDK project does this, for each test.

Here's the code to manage this:
https://github.com/hashicorp/nomad-java-sdk/blob/master/testkit/src/main/java/com/hashicorp/nomad/testutils/NomadAgentProcess.java

Here's an example using it:
https://github.com/hashicorp/nomad-java-sdk/blob/master/testkit/src/test/java/com/hashicorp/nomad/javasdk/JobsApiTest.java#L120

**Comment by cgbaker** [comment]
this stuff lives in the nomad-testkit library:
https://mvnrepository.com/artifact/com.hashicorp.nomad/nomad-testkit

**Comment by cricket007** [comment]
Okay, this is what I was looking for 

https://github.com/hashicorp/nomad-java-sdk/blob/master/testkit/src/main/java/com/hashicorp/nomad/testutils/AugmentedProcess.java#L25

However, that still requires building Nomad with the `nomad_test` flag? Or is that binary available to download somewhere?

**Comment by cgbaker** [comment]
Our test suite requires Nomad built with that flag, to enable mock_driver.
It would be possible to distribute that driver separately (because we
support plugins now). Also, if your integration testing uses one of the
built-in drivers, then you can use a factory Nomad binary.

**Comment by cricket007** [comment]
Yeah, think I'd stick with the mock driver since I just want to verify the API calls are working as expected, not actually starting any services. 

Should I make a separate ticket that requests the Nomad build process outputs&uploads the test artifact somewhere?

**Comment by cgbaker** [comment]
You can make that request against the Nomad repo.

**Comment by cricket007** [comment]
Done! Thanks for the responses!
