### ISSUE TITLE
Path for Job Validation in JobsApi is incorrect

### ISSUE THREAD

**Issue by EikeIsermann** [hashicorp/nomad-java-sdk#8]
Hi there,

thanks for the great sdk, it saved me a lot of work. Nevertheless there is a small typo in 
```java
public ServerResponse<JobValidateResponse> validate(Job job, @Nullable WriteOptions options)
            throws IOException, NomadException {
        return executeServerAction(
                put("/v1/job/validate", new JobValidationRequest(job), options),
                NomadJson.parserFor(JobValidateResponse.class));
    }
```
If I'm not wrong, the actual path for validation requests is /v1/validate/job as seen here: https://www.nomadproject.io/api/validate.html

I've changed the path and created a pull request already #7

Best regards
Eike

**Comment by dadgar** [comment]
Fixed by #7
