### ISSUE TITLE
Not able to get your config class working, does not exist 

### ISSUE THREAD

**Issue by alexanderm2018** [hashicorp/nomad-java-sdk#9]
I have tried 3 latest version none of them were able to resolve your class, could you update your examples.
NomadApiClientConfiguration config =
        new NomadApiClientConfiguration.Builder()
                .setAddress("192.168.0.1:4646")
                .build();

**Comment by cwdesautels** [comment]
I noticed this while I was using the sdk as well, I believe it was renamed to 'NomadApiConfiguration' the below code is working for me.

```
        NomadApiConfiguration nomadConfig = new NomadApiConfiguration.Builder()
                .setAddress(address)
                .setAuthToken(aclToken)
                .setTlsCaFile(cacertPath)
                .setRegion(region)
                .build();

        NomadApiClient nomadClient = new NomadApiClient(nomadConfig);
```

**Comment by cgbaker** [comment]
I fixed this in the README, thanks.
